library(rtweet)
# BLM
df1 <- search_tweets("BLM", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df2 <- search_tweets("george floyd", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df3 <- search_tweets("breonna taylor", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df4 <- search_tweets("black lives matter", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df5 <- search_tweets("blacklivesmatter", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df6 <- search_tweets("all lives matter", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df7 <- search_tweets("thin blue line", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df8 <- search_tweets("police brutality", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df9 <- search_tweets("defund the police", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df10 <- search_tweets("defundthepolice", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
study1_df <- rbind(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10)
rm(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10)
library(dplyr)
length(unique(study1_df$text)) #98641 unique tweets 
# Cuomo
df1 <- search_tweets("cuomo", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df2 <- search_tweets("cuomo resignation", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df3 <- search_tweets("cuomo allegations", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df4 <- search_tweets("cuomo sexual assault", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df5 <- search_tweets("cuomo sexual abuse", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df6 <- search_tweets("governor cuomo", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
study2_df <- rbind(df1,df2,df3,df4,df5,df6)
rm(df1,df2,df3,df4,df5,df6)
length(unique(study2_df$text)) #49996 unique tweets
# Covid Vaccine Hesitancy 
df1 <- search_tweets("pfizer", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df2 <- search_tweets("moderna", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df3 <- search_tweets("j&j", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df4 <- search_tweets("covaxin", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df5 <- search_tweets("vaccine hesitancy", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df6 <- search_tweets("vaccine injury", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df7 <- search_tweets("antivax", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
df8 <- search_tweets("booster shot", n = 100000, include_rts = FALSE, lang="en", verified = FALSE, retryonratelimit = TRUE)
study3_df <- rbind(df1,df2,df3,df4,df5,df6,df7,df8)
rm(df1,df2,df3,df4,df5,df6,df7,df8)
library(dplyr)
length(unique(study3_df$text)) #338903 unique tweets